CREDIT_CARDS = [
    {
        'id': 'chase-sapphire-preferred',
        'name': 'Chase Sapphire Preferred',
        'issuer': 'Chase',
        'network': 'Visa',
        'annual_fee': 95,
        'min_credit_score': 670,
        'min_income': 30000,
        'min_age': 18,
        'rewards': {'dining': 3, 'grocery': 3, 'travel': 2, 'streaming': 3, 'gas': 1, 'shopping': 1, 'other': 1},
        'signup_bonus': 750,
        'bonus_spend': 4000,
        'bonus_timeframe': '3 months',
        'best_for': 'Travel & Dining',
        'best_for_icon': '\u2708\ufe0f',
        'perks': [
            'No foreign transaction fees',
            '$50 annual hotel credit via Chase Travel',
            'Trip cancellation & interruption insurance',
            'Primary auto rental collision coverage',
            'Points worth 25% more when redeemed through Chase Travel',
        ],
        'apply_link': 'https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred',
        'card_gradient': 'linear-gradient(135deg, #1a1f5e 0%, #3d52b0 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': True,
        'description': 'The benchmark travel card \u2014 strong rewards on dining and travel with a reasonable annual fee.',
    },
    {
        'id': 'chase-sapphire-reserve',
        'name': 'Chase Sapphire Reserve',
        'issuer': 'Chase',
        'network': 'Visa',
        'annual_fee': 550,
        'min_credit_score': 740,
        'min_income': 60000,
        'min_age': 18,
        'rewards': {'dining': 3, 'travel': 3, 'grocery': 1, 'gas': 1, 'streaming': 1, 'shopping': 1, 'other': 1},
        'signup_bonus': 600,
        'bonus_spend': 4000,
        'bonus_timeframe': '3 months',
        'best_for': 'Premium Travel',
        'best_for_icon': '\U0001f48e',
        'perks': [
            '$300 annual travel credit',
            'Priority Pass Select lounge access',
            'Global Entry/TSA PreCheck credit ($100)',
            'No foreign transaction fees',
            'Points worth 50% more through Chase Travel',
        ],
        'apply_link': 'https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve',
        'card_gradient': 'linear-gradient(135deg, #1a1a1a 0%, #4a4a4a 100%)',
        'card_text_color': '#c8a84b',
        'no_foreign_fee': True,
        'description': 'The ultimate travel card for frequent flyers with premium lounge access and travel credits.',
    },
    {
        'id': 'chase-freedom-unlimited',
        'name': 'Chase Freedom Unlimited',
        'issuer': 'Chase',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 3, 'grocery': 1, 'gas': 1, 'travel': 1.5, 'streaming': 1.5, 'shopping': 1.5, 'other': 1.5},
        'signup_bonus': 200,
        'bonus_spend': 500,
        'bonus_timeframe': '3 months',
        'best_for': 'Everyday Cashback',
        'best_for_icon': '\U0001f4b5',
        'perks': [
            '1.5% on all purchases with no cap',
            '3% on dining and drugstores',
            'No annual fee',
            'Pairs perfectly with Sapphire cards',
            'Cell phone protection',
        ],
        'apply_link': 'https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited',
        'card_gradient': 'linear-gradient(135deg, #1565c0 0%, #42a5f5 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Simple, powerful cashback on everything \u2014 no rotating categories, no annual fee.',
    },
    {
        'id': 'chase-freedom-flex',
        'name': 'Chase Freedom Flex',
        'issuer': 'Chase',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 3, 'grocery': 1, 'gas': 2.5, 'travel': 1, 'streaming': 1, 'shopping': 2.5, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 500,
        'bonus_timeframe': '3 months',
        'best_for': 'Rotating Categories',
        'best_for_icon': '\U0001f504',
        'perks': [
            '5% on rotating quarterly categories (up to $1,500/quarter)',
            '3% on dining and drugstores',
            'No annual fee',
            'Cell phone protection',
            'Purchase protection up to $500',
        ],
        'apply_link': 'https://creditcards.chase.com/cash-back-credit-cards/freedom/flex',
        'card_gradient': 'linear-gradient(135deg, #1565c0 0%, #e64a19 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Maximize rewards with 5% cash back on rotating quarterly categories.',
    },
    {
        'id': 'amazon-prime-rewards-visa',
        'name': 'Amazon Prime Rewards Visa',
        'issuer': 'Chase',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 2, 'grocery': 5, 'gas': 2, 'travel': 1, 'streaming': 1, 'shopping': 5, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 0,
        'bonus_timeframe': 'upon approval',
        'best_for': 'Amazon & Whole Foods',
        'best_for_icon': '\U0001f4e6',
        'perks': [
            '5% back on Amazon and Whole Foods',
            '$200 Amazon Gift Card upon approval',
            'No annual fee (requires Prime membership)',
            '2% at restaurants, gas stations, drugstores',
            'No foreign transaction fees',
        ],
        'apply_link': 'https://www.amazon.com/Amazon-Prime-Rewards-Visa-Signature-Card/dp/BT00LN946S',
        'card_gradient': 'linear-gradient(135deg, #00171f 0%, #005073 100%)',
        'card_text_color': '#ff9900',
        'no_foreign_fee': True,
        'description': 'The must-have card for Amazon Prime members \u2014 5% back on every Amazon and Whole Foods purchase.',
    },
    {
        'id': 'amex-gold',
        'name': 'Amex Gold',
        'issuer': 'Amex',
        'network': 'Amex',
        'annual_fee': 250,
        'min_credit_score': 700,
        'min_income': 45000,
        'min_age': 18,
        'rewards': {'dining': 4, 'grocery': 4, 'travel': 3, 'gas': 1, 'streaming': 1, 'shopping': 1, 'other': 1},
        'signup_bonus': 750,
        'bonus_spend': 6000,
        'bonus_timeframe': '6 months',
        'best_for': 'Dining & Groceries',
        'best_for_icon': '\U0001f37d\ufe0f',
        'perks': [
            '$120 dining credit ($10/month at select restaurants)',
            '$120 Uber Cash annually',
            'No foreign transaction fees',
            '$100 hotel credit via Amex Travel',
            'Extended warranty protection',
        ],
        'apply_link': 'https://www.americanexpress.com/us/credit-cards/card/gold-card/',
        'card_gradient': 'linear-gradient(135deg, #b8860b 0%, #ffd700 100%)',
        'card_text_color': '#1a1a1a',
        'no_foreign_fee': True,
        'description': 'Unmatched dining and grocery rewards \u2014 the card that pays for itself if you eat out often.',
    },
    {
        'id': 'amex-platinum',
        'name': 'Amex Platinum',
        'issuer': 'Amex',
        'network': 'Amex',
        'annual_fee': 695,
        'min_credit_score': 740,
        'min_income': 75000,
        'min_age': 18,
        'rewards': {'dining': 1, 'grocery': 1, 'travel': 5, 'gas': 1, 'streaming': 1, 'shopping': 1, 'other': 1},
        'signup_bonus': 800,
        'bonus_spend': 8000,
        'bonus_timeframe': '6 months',
        'best_for': 'Luxury Travel',
        'best_for_icon': '\U0001f31f',
        'perks': [
            '$200 hotel credit via Fine Hotels + Resorts',
            '$200 airline fee credit',
            'Centurion & Priority Pass lounge access (1,400+ lounges)',
            '$240 digital entertainment credit',
            'Global Entry/TSA PreCheck credit',
        ],
        'apply_link': 'https://www.americanexpress.com/us/credit-cards/card/platinum/',
        'card_gradient': 'linear-gradient(135deg, #757575 0%, #d4d4d4 100%)',
        'card_text_color': '#1a1a1a',
        'no_foreign_fee': True,
        'description': 'The ultimate luxury travel card with unparalleled lounge access and travel credits worth over $1,500/year.',
    },
    {
        'id': 'blue-cash-preferred',
        'name': 'Blue Cash Preferred',
        'issuer': 'Amex',
        'network': 'Amex',
        'annual_fee': 95,
        'min_credit_score': 670,
        'min_income': 25000,
        'min_age': 18,
        'rewards': {'dining': 1, 'grocery': 6, 'gas': 3, 'travel': 1, 'streaming': 6, 'shopping': 1, 'other': 1},
        'signup_bonus': 350,
        'bonus_spend': 3000,
        'bonus_timeframe': '6 months',
        'best_for': 'Groceries & Streaming',
        'best_for_icon': '\U0001f6d2',
        'perks': [
            '6% at U.S. supermarkets (up to $6,000/year)',
            '6% on select U.S. streaming services',
            '3% at U.S. gas stations',
            '3% on transit (rideshare, parking, tolls)',
            '$84 Disney Bundle credit annually',
        ],
        'apply_link': 'https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/',
        'card_gradient': 'linear-gradient(135deg, #003087 0%, #0066cc 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'The top choice for families \u2014 unbeatable 6% cash back at U.S. supermarkets and on streaming.',
    },
    {
        'id': 'blue-cash-everyday',
        'name': 'Blue Cash Everyday',
        'issuer': 'Amex',
        'network': 'Amex',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 1, 'grocery': 3, 'gas': 3, 'travel': 1, 'streaming': 1, 'shopping': 3, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 2000,
        'bonus_timeframe': '6 months',
        'best_for': 'No-Fee Groceries',
        'best_for_icon': '\U0001f966',
        'perks': [
            '3% at U.S. supermarkets (up to $6,000/year)',
            '3% at U.S. gas stations',
            '3% on U.S. online retail purchases',
            'No annual fee',
            '$84 Disney Bundle credit annually',
        ],
        'apply_link': 'https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/',
        'card_gradient': 'linear-gradient(135deg, #005daa 0%, #56acdf 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'A solid no-fee option with 3% cash back on groceries, gas, and online shopping.',
    },
    {
        'id': 'capital-one-venture-x',
        'name': 'Capital One Venture X',
        'issuer': 'Capital One',
        'network': 'Visa',
        'annual_fee': 395,
        'min_credit_score': 740,
        'min_income': 60000,
        'min_age': 18,
        'rewards': {'dining': 2, 'grocery': 2, 'gas': 2, 'travel': 2, 'streaming': 2, 'shopping': 2, 'other': 2},
        'signup_bonus': 750,
        'bonus_spend': 4000,
        'bonus_timeframe': '3 months',
        'best_for': 'Premium Travel Value',
        'best_for_icon': '\U0001f680',
        'perks': [
            '$300 annual travel credit (Capital One Travel)',
            '10,000 bonus miles on anniversary ($100 value)',
            'Priority Pass & Capital One Lounge access',
            'Global Entry/TSA PreCheck credit',
            'No foreign transaction fees',
        ],
        'apply_link': 'https://capitalone.com/credit-cards/venture-x/',
        'card_gradient': 'linear-gradient(135deg, #1c1c1c 0%, #4a2c6e 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': True,
        'description': 'Best value in the premium travel card space \u2014 $300 travel credit almost covers the annual fee alone.',
    },
    {
        'id': 'capital-one-savorone',
        'name': 'Capital One SavorOne',
        'issuer': 'Capital One',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 580,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 3, 'grocery': 3, 'gas': 1, 'travel': 1, 'streaming': 3, 'shopping': 1, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 500,
        'bonus_timeframe': '3 months',
        'best_for': 'Dining & Entertainment',
        'best_for_icon': '\U0001f3ac',
        'perks': [
            '3% on dining, entertainment, groceries, and streaming',
            'No annual fee',
            'No foreign transaction fees',
            'Entertainment access to Capital One experiences',
            'Extended warranty protection',
        ],
        'apply_link': 'https://capitalone.com/credit-cards/savorone/',
        'card_gradient': 'linear-gradient(135deg, #1c1c1c 0%, #5c3d2e 100%)',
        'card_text_color': '#e8c49a',
        'no_foreign_fee': True,
        'description': 'Top no-fee card for dining, entertainment, and streaming \u2014 hard to beat at $0 annual fee.',
    },
    {
        'id': 'capital-one-quicksilver',
        'name': 'Capital One Quicksilver',
        'issuer': 'Capital One',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 580,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'all': 1.5},
        'signup_bonus': 200,
        'bonus_spend': 500,
        'bonus_timeframe': '3 months',
        'best_for': 'Simple Cashback',
        'best_for_icon': '\u26a1',
        'perks': [
            '1.5% cash back on all purchases \u2014 no categories',
            'No annual fee',
            'No foreign transaction fees',
            '$200 cash bonus after $500 spend',
            'One-time purchase price protection',
        ],
        'apply_link': 'https://capitalone.com/credit-cards/quicksilver/',
        'card_gradient': 'linear-gradient(135deg, #78909c 0%, #cfd8dc 100%)',
        'card_text_color': '#1a1f36',
        'no_foreign_fee': True,
        'description': 'Effortless 1.5% cash back on every purchase with no categories to track and no annual fee.',
    },
    {
        'id': 'citi-double-cash',
        'name': 'Citi Double Cash',
        'issuer': 'Citi',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 580,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'all': 2},
        'signup_bonus': 200,
        'bonus_spend': 1500,
        'bonus_timeframe': '6 months',
        'best_for': 'Flat Rate Cashback',
        'best_for_icon': '\U0001f4b0',
        'perks': [
            '2% cash back on all purchases (1% when you buy + 1% when you pay)',
            'No annual fee',
            '$200 welcome bonus',
            'Convert to Citi ThankYou Points',
            'Cell phone protection',
        ],
        'apply_link': 'https://www.citi.com/credit-cards/citi-double-cash-credit-card',
        'card_gradient': 'linear-gradient(135deg, #003b70 0%, #0070bd 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'The benchmark flat-rate cashback card \u2014 earn 2% on everything, automatically.',
    },
    {
        'id': 'citi-custom-cash',
        'name': 'Citi Custom Cash',
        'issuer': 'Citi',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 5, 'grocery': 2, 'gas': 2, 'travel': 1, 'streaming': 1, 'shopping': 1, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 1500,
        'bonus_timeframe': '6 months',
        'best_for': 'Top Category Spenders',
        'best_for_icon': '\U0001f3af',
        'perks': [
            '5% on your top spend category each cycle (up to $500/month)',
            'No annual fee',
            'No rotating categories to track',
            '1% on all other purchases',
            '$200 welcome bonus',
        ],
        'apply_link': 'https://www.citi.com/credit-cards/citi-custom-cash-credit-card',
        'card_gradient': 'linear-gradient(135deg, #3d1c6e 0%, #6b3fa0 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Automatically earns 5% cash back on your top eligible spend category each billing cycle.',
    },
    {
        'id': 'bofa-customized-cash',
        'name': 'Bank of America Customized Cash',
        'issuer': 'BofA',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 1, 'grocery': 2, 'gas': 3, 'travel': 1, 'streaming': 1, 'shopping': 3, 'other': 1},
        'signup_bonus': 200,
        'bonus_spend': 1000,
        'bonus_timeframe': '3 months',
        'best_for': 'Flexible Categories',
        'best_for_icon': '\U0001f527',
        'perks': [
            '3% on your choice category (gas, online shopping, dining, travel, drug stores, or home)',
            '2% at grocery stores and wholesale clubs',
            'No annual fee',
            'Preferred Rewards members earn up to 75% more cash back',
            '$200 welcome bonus',
        ],
        'apply_link': 'https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/',
        'card_gradient': 'linear-gradient(135deg, #c8102e 0%, #e53935 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Choose your own 3% category each month \u2014 ideal if your spending varies.',
    },
    {
        'id': 'bofa-unlimited-cash',
        'name': 'Bank of America Unlimited Cash',
        'issuer': 'BofA',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'all': 1.5},
        'signup_bonus': 200,
        'bonus_spend': 1000,
        'bonus_timeframe': '3 months',
        'best_for': 'BofA Customers',
        'best_for_icon': '\U0001f3e6',
        'perks': [
            'Unlimited 1.5% cash back on all purchases',
            'No annual fee',
            'Preferred Rewards members earn up to 2.625%',
            'No category restrictions',
            '$200 welcome bonus',
        ],
        'apply_link': 'https://www.bankofamerica.com/credit-cards/products/unlimited-cash-back-credit-card/',
        'card_gradient': 'linear-gradient(135deg, #c8102e 0%, #ff6d6d 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Simple 1.5% cash back everywhere \u2014 BofA Preferred Rewards members can earn up to 2.625%.',
    },
    {
        'id': 'bofa-travel-rewards',
        'name': 'Bank of America Travel Rewards',
        'issuer': 'BofA',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'all': 1.5},
        'signup_bonus': 250,
        'bonus_spend': 1000,
        'bonus_timeframe': '3 months',
        'best_for': 'No-Fee Travel',
        'best_for_icon': '\U0001f5fa\ufe0f',
        'perks': [
            '1.5 points per $1 on all purchases',
            'No annual fee',
            'No foreign transaction fees',
            'Redeem points for flights, hotels, and more',
            'Points never expire',
        ],
        'apply_link': 'https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/',
        'card_gradient': 'linear-gradient(135deg, #c8102e 0%, #1565c0 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': True,
        'description': 'Earn travel points on every purchase with no annual fee and no foreign transaction fees.',
    },
    {
        'id': 'discover-it-cash-back',
        'name': 'Discover it Cash Back',
        'issuer': 'Discover',
        'network': 'Discover',
        'annual_fee': 0,
        'min_credit_score': 0,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 2.5, 'grocery': 2.5, 'gas': 2.5, 'travel': 1, 'streaming': 1, 'shopping': 2.5, 'other': 1},
        'signup_bonus': 0,
        'bonus_spend': 0,
        'bonus_timeframe': 'first year',
        'best_for': 'First Credit Card',
        'best_for_icon': '\U0001f31f',
        'perks': [
            'Cashback Match\u2122 \u2014 doubles all rewards earned in year 1',
            '5% on rotating quarterly categories (up to $1,500/quarter)',
            '1% on everything else',
            'Free FICO credit score monitoring',
            'No foreign transaction fees',
        ],
        'apply_link': 'https://www.discover.com/credit-cards/cash-back/it-card.html',
        'card_gradient': 'linear-gradient(135deg, #f46c1a 0%, #f9a01b 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': True,
        'description': 'The best card for building or starting credit \u2014 Discover matches ALL cash back earned in your first year.',
    },
    {
        'id': 'wells-fargo-active-cash',
        'name': 'Wells Fargo Active Cash',
        'issuer': 'Wells Fargo',
        'network': 'Visa',
        'annual_fee': 0,
        'min_credit_score': 670,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'all': 2},
        'signup_bonus': 200,
        'bonus_spend': 500,
        'bonus_timeframe': '3 months',
        'best_for': 'Flat Rate Alternative',
        'best_for_icon': '\U0001f48e',
        'perks': [
            'Unlimited 2% cash rewards on purchases',
            'No annual fee',
            '$200 cash rewards welcome bonus',
            'Cell phone protection (up to $600)',
            'Visa Signature concierge service',
        ],
        'apply_link': 'https://creditcards.wellsfargo.com/active-cash-credit-card',
        'card_gradient': 'linear-gradient(135deg, #cc0000 0%, #ff6b35 100%)',
        'card_text_color': '#ffffff',
        'no_foreign_fee': False,
        'description': 'Unlimited 2% cash back on all purchases with a generous welcome bonus and cell phone protection.',
    },
    {
        'id': 'apple-card',
        'name': 'Apple Card',
        'issuer': 'Apple',
        'network': 'Mastercard',
        'annual_fee': 0,
        'min_credit_score': 580,
        'min_income': 0,
        'min_age': 18,
        'rewards': {'dining': 1, 'grocery': 1, 'gas': 1, 'travel': 1, 'streaming': 1, 'shopping': 3, 'other': 1},
        'signup_bonus': 0,
        'bonus_spend': 0,
        'bonus_timeframe': '',
        'best_for': 'Apple Ecosystem Users',
        'best_for_icon': '\U0001f34e',
        'perks': [
            '3% back on all Apple purchases',
            '2% back with Apple Pay (most transactions)',
            'Daily Cash deposited to Apple Cash every day',
            'No annual fee, no late fees, no foreign fees',
            'Built-in spending insights in the Wallet app',
        ],
        'apply_link': 'https://www.apple.com/apple-card/',
        'card_gradient': 'linear-gradient(135deg, #e8e8ed 0%, #f5f5f7 100%)',
        'card_text_color': '#1a1f36',
        'no_foreign_fee': True,
        'description': 'Beautifully simple cash back card designed for iPhone users \u2014 no fees of any kind.',
    },
]
